#!/usr/bin/env python3

from sys import argv
from os import listdir, chdir, system

from pytube import YouTube
from mutagen.easyid3 import EasyID3


def main():
    if len(argv) > 1:
        list_filename = argv[1].strip()
    else:
        list_filename = 'songs.lst'

    if len(argv) > 2:
        destination = argv[2].strip()
    else:
        destination = 'songs'

    songs = []
    with open(list_filename, 'r') as list_file:
        for line in list_file:
            if not line.strip() == '':
                parts = [part.strip() for part in line.strip().split('|')]
                songs.append({'url': parts[0], 'title': parts[1], 'artist': parts[2], 'album': parts[3]})

    if destination not in listdir():
        mkdir(destination)
    chdir(destination)

    for song in songs:
        yt = YouTube(song['url'])
        stream = yt.streams.filter(only_audio=True, audio_codec='mp4a.40.2').first()
        if not stream:
            stream = yt.streams.filter(audio_codec='mp4a.40.2').first()
        stream.download(filename=song['title'])

        system('avconv -i "' + song['title'] + '.mp4" "' + song['title'] + '.mp3"')

        audio = EasyID3(song['title'] + '.mp3')
        audio['title'] = song['title']
        audio['artist'] = song['artist']
        audio['album'] = song['album']
        audio.save()

        print(song['title'] + '.mp3 succeeded')

if __name__ == '__main__':
    main()

